// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter, Cinzel, Roboto } from "next/font/google"; // Tambahkan Roboto di sini
import "./globals.css";
import { AuthProvider } from "@/lib/auth-context";

// Inisialisasi font Cinzel. Kita akan menggunakan ini untuk seluruh body.
const cinzel = Cinzel({
  subsets: ['latin'],
  weight: ['400', '700'], // Bobot yang umum digunakan untuk teks
  display: 'swap',
  variable: '--font-cinzel', // Tambahkan variabel CSS untuk Cinzel
});

// Inisialisasi font Roboto untuk placeholder
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400'], // Bobot yang umum digunakan untuk placeholder
  display: 'swap',
  variable: '--font-roboto', // Tambahkan variabel CSS untuk Roboto
});

// Mengatur font Inter sebagai fallback atau untuk elemen lain
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Terapkan font Cinzel sebagai default dan sediakan variabel Roboto */}
      <body className={`${cinzel.className} ${roboto.variable}`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
